### ISSUE TITLE
Its just not working

### ISSUE THREAD

**Issue by NORXND** [ItzSplash/antispam#2]
When I started spamming, nothing heppends

**Comment by ItzSplash** [comment]
Yeah I made this about 2 years ago, probably incompatible on current discord, I will come back to it eventually, if you are to add the errors I would gladly repair them

**Comment by NORXND** [comment]
I dont mean error, it wont stop spam (Sending so much messages in short time), but it in wrong verion too.

**Comment by NORXND** [comment]
For real, I dont test it. I just see code
